name: Deploy ECS-EC2

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: ./terraform
        run: terraform plan -var-file="dev.tfvars" -out=tfplan

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply tfplan
        
      - name: Get Terraform Outputs
        id: get-outputs
        working-directory: ./terraform
        run: |
          terraform output -json > tf-outputs.json
          echo "S3_BUCKET_NAME=$(jq -r '.s3_bucket_name.value' tf-outputs.json)" >> $GITHUB_ENV
 
      - name: Zip Lambda Function
        run: |
          cd terraform/Modules/lambda
          zip -r lambda_function.zip lambda_function.py
          mv lambda_function.zip ../../

      - name: Upload to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ env.S3_BUCKET_NAME }}
          source: lambda_function.zip
          region: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
      - name: Update Lambda Function Code
        uses: aws-actions/aws-lambda-update-function-code@v1
        with:
          function-name: "my-python-lambda"
          s3-bucket: ${{ env.S3_BUCKET_NAME }}
          s3-key: "lambda_function.zip"
          region: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}