name: Deploy ECS-EC2

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Zip Lambda Function
        working-directory: ./terraform
        run: |
          cd Modules/lambda
          zip -r lambda_function.zip lambda_function.py
          mv lambda_function.zip ../../

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: ./terraform
        run: terraform plan -var-file="dev.tfvars" -out=tfplan

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply tfplan
 
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
 
      - name: Upload Lambda to S3
        working-directory: ./terraform
        run: |
          aws s3 cp lambda_function.zip s3://${{ secrets.BUCKET_NAME }}/lambda_function.zip
        env:
          region: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
      - name: Update Lambda Function Code using AWS CLI
        working-directory: ./terraform
        run: |
          aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION }} --s3-bucket ${{ secrets.BUCKET_NAME }} --s3-key lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
          